version: '3'

services:
  todosDB:
    image:  postgres:15.3
    container_name: practice-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mago
      - POSTGRES_PASSWORD=mago
    volumes:
      - ./postgres:/var/lib/postgresql/data
